const service_data = {
  1: {
    items: [
      {
        name: "Talk to a Lawyer",
        id: 1,

        desc: "100% Confidentiality",
        middesc: "Approachable and Solution-focused attorneys",
        enddesc: "Guaranteed Satisfaction, or Full Refund",
      },
      {
        name: "Talk to a CA",
        id: 2,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "200+ Verified Experts",
        middesc: "No Hidden Costs",
        enddesc: "Guaranteed Satisfaction, or Full Refund",
      },
      {
        name: "Talk to a CS",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "200+ Verified Experts",
        middesc: "Friendly Advice on all compliances",

        enddesc: "Guaranteed Satisfaction, or Full Refund",
      },
      {
        name: "Talk to a IP/Trademark Lawyer",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Expert IP lawyers assist you get your trademark, Patent, Copyright or Design registered",
        middesc: "Guided assistance via chat throughout the process",
        enddesc: "Get a lawyer call back in less than 24 hours",
      },
    ],
  },
  2: {
    items: [
      {
        name: "GST Registration",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "GST Registration in 7 business days",
        middesc:
          "Enjoy hassle-free processing as Vakilsearch lays the groundwork for your business.",
        enddesc: "",
      },
      {
        name: "GST Filing",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Guaranteed GST filing at the government portal under 24 hrs by top CA’s",
        middesc:
          "Get MSME Registration and your annual returns filed before the deadline",
        enddesc: "Guaranteed Satisfaction, or Full Refund",
      },

      {
        name: "GST Advisory",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Now govern all the input taxes of your company in just a few clicks thanks to the Vakilsearch GST advice portal!",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Indirect Tax",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Experienced tax professionals can help you comprehend the official notification and aid in creating suitable clarifications T&C* ",
        middesc:
          "3-step easy online process.Support with documentation & registration",
        enddesc: "",
      },
      {
        name: "Add a Director",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "From getting a DIN for the new director, drafting the resolution, to filing Form DIR-12, we take care of everything!",
        middesc:
          "Get the process started at just ₹499/- and pay the rest conveniently after processing begins.",
        enddesc: "",
      },
      {
        name: "Remove a Director",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Remove a company director without any legal implications in just 10 days T&C* ",
        middesc:
          "Complete the process online, starting from a price of ₹2500 + taxes.",
        enddesc: "",
      },
      {
        name: "Increase Authorized Capital",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Do you want to increase your company’s share capital base? Vakilsearch’s experts will set up your compliances and documents",
        middesc:
          "Package includes alteration of AOA, MOA, drafting of resolutions, & filing of forms with ROC.",
        enddesc: "",
      },
      {
        name: "Close the Pvt Ltd Company",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Liquidate your company without any hassles and without breaching any compliances. Talk to an expert from Vakilsearch right now!",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Change Objective/Activity",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "With Vakilsearch, you can amend your company’s goals in your MoA easily and quickly!",
        middesc:
          "Get the process started at just ₹99/- and pay the rest conveniently after processing begins.",
        enddesc: "",
      },
      {
        name: "Change Address",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Change your company address without any hassles. ROC filing done by top legal experts. Both Instate and inter-state address changes are handled seamlessly.",
        middesc:
          "3 easy step process, Complete paperwork support, and 100% online.",
        enddesc: "",
      },
      {
        name: "Change Company Name",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Change your company name with MCA compliance. Service includes name availability search, name approval & complete documentation",
        middesc:
          "We draft applications for approval of company name change and file them with the registrar of companies",
        enddesc: "",
      },
      {
        name: "Add Designated Partner",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Every Limited Liability Partnership must have at least two designated partners. To add a designated partner, a resolution needs to be passed. He must have a DPIN and his name must be amended in the LLP agreement.",
      },
      {
        name: "Changes to LLP Agreement",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Get your LLP agreement amended without breaching any compliance. Form 3 filing done by compliance experts",
        middesc: "100% online process. Hasslefree paperwork by our experts",
        enddesc: "",
      },
      {
        name: "Close the LLP",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "An LLP can be closed, if it has not commenced business or is not engaged in the activity of business for the last 1 year. The closure application needs to be filed with the mutual consent of all the partners of the firm.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Private Limited Company / OPC",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        paragraph:
          "With Vakilsearch by your side, it is easy, and can be completed in just a few clicks, that too starts from ₹4,999 for a whole FINANCIAL YEAR! T&C* ",
        desc: "Easy process",
        middesc: "Fast and hassle-free",
        enddesc: "Availability of In-house experts",
      },
      {
        name: "Limited Liability Partnership",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "LLPs need to file their returns and statement of accounts annually. Failing to comply with this can attract a penalty of up to Rs 5 lakh. Annual Compliance comprises.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "CFSS",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Enjoy a one-time waiver of additional filing fees for all delayed filings up to 30th September 2020. Thanks to Companies Fresh Start Scheme 2020 and revised LLP Settlement Scheme 2020!",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Provident Fund (PF) Registration",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Fastest registration turnaround time in India with Guaranteed application filing in 3 days or get a full refund T&C* ",
        middesc: "Track the progress of your application anytime, anywhere",
        enddesc: "",
      },
      {
        name: "ESI Registration",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Provide ESIC benefits to your employees by getting an ESI Registration. 100% Online and safe process.",
        middesc: "Transparent process, thorough follow up and regular updates",
        enddesc: "",
      },
      {
        name: "Professional Tax Registration",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "We collect all the required information",
        middesc: "We will appoint an affiliate to process your application",
        enddesc: "The TIN will be issue within 15 days of the application",
      },
      {
        name: "Shops and Establishments License",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Fastest turnaround time in India to get your Shop and Establishment License T&C*",
        middesc:
          "Documents will be filed by our shop and establishment registration Expert with the state labour departments",
        enddesc: "",
      },
      {
        name: "Employee Stock Option Plan [ESOP]",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "ESOP is an effective employee retention strategy with which a company provides stock options to its employees so that they stick around and remain motivated.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "POSH Compliance",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "With Vakilsearch, you can create and customise Employee-To-Employee POSH compliance programs to fit your own business needs.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Accounting and Book-keeping",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        paragraph:
          "Now save upto 90% on your accountant fee. Avail accounting and bookkeeping services for a whole year at just ₹12999!",
        desc: "Bookkeeping of assets, sales, purchases, and expenses",
        middesc: "Get your balance sheet, audit and director's report prepared",
        enddesc: "Filing of ITR",
      },
      {
        name: "Payroll Maintenance",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Upgrade yourself to the amazing online payroll management system from Vakilsearch, Say goodbye to the hassle of manual payroll management!",
        middesc: "",
        enddesc: "",
      },
      {
        name: "TDS Return Filing",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "File your TDS/TCS returns on-time and avoid penalties. E-filing done by Top Accountants and TAX experts",
        middesc:
          "3 step online process, 100% safe, TDS filed for both businesses and Individuals",
        enddesc: "",
      },
      {
        name: "Individual Income Tax Filing",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "An LLP can be closed, if it has not commenced business or is not engaged in the activity of business for the last 1 year. The closure application needs to be filed with the mutual consent of all the partners of the firm.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Proprietorship Tax Return Filing",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "For converting a sole partnership to a Private Limited Company (PLC), you need to submit an agreement between the sole proprietor and the PLC declaring the transfer of all assets.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Income Tax Notice",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "We recognize the notification type and the filing discrepancy. T&C* ",
        middesc: "Next, we will draft explanations for the notices",
        enddesc: "",
      },
      {
        name: "Proprietorship to Pvt Ltd Company",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "For converting a sole partnership to a Private Limited Company (PLC), you need to submit an agreement between the sole proprietor and the PLC declaring the transfer of all assets.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Compliance Check - Secretarial Audit",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "A Secretarial Audit is done to check the compliance of different legislations (like the Companies Act) and other economic and corporate laws, rules and procedures applicable to an organization.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Due Digilence",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Conduct all your company's legal and financial diligence in just a few clicks with Vakilsearch. Get a due diligence report and gain trust from your investor!.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Partnership to LLP",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Convert your Partnership into an LLP. DSC, DPIN, LLP forms procured and filed by legal experts",
        middesc:
          "100% online process. Holistic support for license transfer, and post-conversion legalities",
        enddesc: "",
      },
      {
        name: "Private to Public Limited Company",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "A Public Limited Company is a company that has limited liability and its shares can be freely traded and sold to the public. For converting a private to a Public Limited Company under Companies Act 2013, you need to have at least 3 directors, 7 shareholders and a paid-up capital of ₹5 lakhs.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Private to One Person Company",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "One Person Company (OPC) can be formed with only 1 owner, who acts as both the director as well as a shareholder of the company. There can be more than 1 director, but not more than 1 shareholder. For converting a Private Limited Company to an OPC, your paid-up capital and annual turnover should be less than ₹50 lakh and ₹2 Crore respectively.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "RBI Compliance",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Tackle the offences on time and avoid prosecution. Opt for RBI compounding quickly. Filing done by top experts",
        middesc: "Fast and secure processing, Legal experts assistance.",
        enddesc: "",
      },
    ],
  },
  3: {
    items: [
      {
        name: "Private Limited Company",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        paragraph:
          "With Vakilsearch by your side, it is easy, and can be completed in just a few clicks, that too starts from ₹4,999 for a whole FINANCIAL YEAR! T&C*",
        desc: "Easy process",
        middesc: "Fast and hassle-free",
        enddesc: "Availability of In-house experts",
      },
      {
        name: "Limited Liability Partnership",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",

        desc: "LLPs need to file their returns and statement of accounts annually. Failing to comply with this can attract a penalty of up to Rs 5 lakh. Annual Compliance comprises.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "One Person Company",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Get your application submitted within 10 Days",
        middesc: "Transparent process, thorough follow up and regular updates",
        enddesc: "",
      },
      {
        name: "Sole Proprietorship",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Fastest registration turnaround time in India with Guaranteed document upload to the government portal under 7 days or get a full refund T&C* ",
        middesc: "Transaparent process, thorough follow up and regular updates",
        enddesc: "",
      },
      {
        name: "Nidhi Company",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "An excellent option for people looking to save money and lead a thrifty lifestyle.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Producer Company",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Effortlessly register your Farmer Producer Company under the Ministry of Corporate Affairs",
        middesc: "Transparent process, thorough follow up and regular updates",
        enddesc: "",
      },
      {
        name: "Partnership Firm",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Partnership firm registration deed drafted within 3 days, completely online & hasslefree T&C* ",
        middesc: "Transparent process through follow-up and regular updates",
        enddesc: "",
      },
      {
        name: "Startup India Registration",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Register under the start up India scheme via Vakilsearch and get a certificate in just 3 to 5 working days. Safe end-to-end online process",
        middesc:
          "Submit just 3 documents and kick-start the whole process online now",
        enddesc: "",
      },
      {
        name: "US Incorporation",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Get your USA company incorporated in just 10 working days T&C* ",
        middesc:
          "Your Employer Identification Number is delivered within 48hrs",
        enddesc: "",
      },
      {
        name: "Singapore Incorporation",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Starting a business in Singapore is a challenging yet exciting proposition. While the law in Singapore is very business friendly, there are lots of legalities and red tape that need attending to, which means you need the experts from Vakilsearch on the job.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "UK Incorporation",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        paragraph:
          "Take your business abroad. Incorporate a company in the UK easily through Vakilsearch!",
        desc: "Easy process",
        middesc: "Expert guidance",
        enddesc: "Online process",
      },
      {
        name: "Netherlands Incorporation",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "There is an ease of doing business in the Netherlands. Choose a business structure, trade name, and register as an employer for social security and payroll taxes. Consider environmental regulations and fire safety requirements also while setting up a business there.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Hong Kong Incorporation",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Introduce your business to one of the most bustling markets in the world, Hong Kong. Vakilsearch can help incorporate your company in Hong Kong in just a few easy steps.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Dubai Incorporation",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Get your company name registered in under 24 hrs and receive a lifetime free visa with 100% tax exemption and ownership of your company",
        middesc:
          "Complete secrecy of operations with lower renewal charges & zero import or export duties",
        enddesc: "",
      },
      {
        name: "Company Name Search",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Search the MCA database here & With our experts, Get a 7 day Guaranteed document upload to the MCA or receive a full refund. T&C* ",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Digital Signature Certificate",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Want to buy a DSC online and quickly? Vakilsearch is India's best provider of digital signatures. For just ₹1499, we can provide a Class 3 DSC and digital signature certificate online registration in just 3 easy steps!",
        middesc: "",
        enddesc: "",
      },
      {
        name: "MSME/SSI Registration",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Fastest turnaround time in India with Guaranteed document upload to the government portal under 24 hrs or receive a full refund T&C* ",
        middesc: "Get a 50% discount on your Trademark Govt. Fees",
        enddesc: "",
      },
      {
        name: "ISO Certification",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "With Vakilsearch, you can create and customise Employee-To-Employee POSH compliance programs to fit your own business needs.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "FSSAI Registration Online",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Fastest registration turnaround time in India with Guaranteed document upload to the government portal under 24 hrs or get a full refund T&C* ",
        middesc: "",
        enddesc: "",
      },
      {
        name: "IEC [Import/Export Code]",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Guaranteed submission of IEC application within two days in the DGFT office T&C* ",
        middesc:
          "Make your business global. Apply from anywhere in India with IEC code",
        enddesc: "",
      },
      {
        name: "Legal Metrology",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Complete your LMPC registration and gain your customer's trust.",
        middesc: "Hassle free process, fast, secure and 100% online",
        enddesc: "",
      },
      {
        name: "Hallmark Registration",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Gain a competitive edge in the Indian market with BIS hallmark certification.Give your customers peace of mind by certifying that your products meet the highest standards of safety and quality. T&C* ",
        middesc: "Our experts ensure a hassle-free registration process",
        enddesc: "",
      },
      {
        name: "BIS Registration",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "With Vakilsearch, you can create and customise Employee-To-Employee POSH compliance programs to fit your own business needs.",
        middesc:
          "Boost your product credibility with an ISI mark. Now @ ₹4,500",
        enddesc: "Expert support throughout the BIS registration process.",
      },
      {
        name: "Web/E-Commerce Website Development",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Craft a customized and visually stunning website with our designers & developers",
        middesc:
          "Our experts brainstorm ideas that reflect your unique vision. Get annual maintenance support",
        enddesc: "",
      },
    ],
  },
  4: {
    items: [
      {
        name: "Trademark Registration",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Guaranteed TM application within 24 hrs, online & hasslefree T&C* ",
        middesc:
          "Transparent process through follow-up and regular updates. File your TM at₹1999 +taxes",
        enddesc: "",
      },
      {
        name: "Search for Trademark",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Use Vakilsearch's proprietary online search algorithm to check your brand name availability. With our TM experts, get a Guaranteed 1 day Trademark filing. T&C* ",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Respond to TM Objection",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Approved draft gets uploaded under 48 hrs or receive a full refund T&C* ",
        middesc:
          "Fastest turnaround time in India with Guaranteed document drafting by senior IP lawyers in under 24 hrs",
        enddesc: "",
      },
      {
        name: "Respond to TM Objection",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Approved draft gets uploaded under 48 hrs or receive a full refund T&C* ",
        middesc:
          "Fastest turnaround time in India with Guaranteed document drafting by senior IP lawyers in under 24 hrs",
        enddesc: "",
      },
      {
        name: "Well Known Trademark",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        paragraph:
          "Yes..even popular brands need protection, get in touch with us and quickly procure a well-known trademark status to your brand!",
        desc: "Quick protection of well-known trademarks",
        middesc: "Talk to expert attorneys",
        enddesc: "Get a clear road map",
      },
      {
        name: "Trademark Watch",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Keep track of attempts to register a trademark that’s highly similar or identical to your brand name.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Trademark Renewal",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Now protect your brand identity by renewing your trademark in just a few clicks",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Trademark Assignment",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "The process of transferring ownership of the trademark (symbol, word, number, or even a mix of colors) either with or without the goodwill of the business is called Trademark Assignment. Get your trademark assigned online with Vakilsearch.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "USA Trademark",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        paragraph: "Registering US TM with Vakilsearch gives you:",
        desc: "A reliable and cost effective way to TM in US",
        middesc:
          "A team of experts that understand the Indian business needs the best",
        enddesc: "World-class service",
      },
      {
        name: "International Trademark",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "With the help of Vakilsearch and our expert team, it's easy to protect your brand's credibility and win the trust of customers in international markets.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Logo Design",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Our Logo Designers create a strong visual identity that represents your brand.",
        middesc: "Top designers ensure quick delivery with iterations",
        enddesc: "",
      },
      {
        name: "Copyright Registration",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Register a copyright to protect your creative work, regulate its use, and fight infringement.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Indian Patent Search",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Our IP experts ensure a thorough and accurate patent search to ensure a hasslefree patent filing process later",
        middesc: "Online process with transparent pricing hasslefree process",
        enddesc: "",
      },
      {
        name: "Provisonal Application",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Protect your innovation by filing a provisional patent with our IP experts",
        middesc:
          "Complete documentation and filing support with online process",
        enddesc: "",
      },
      {
        name: "Permanent Patent",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "File for Patent Registration online and protect your Inventions for 20 years",
        middesc: "Experts assisted Patent search and application process",
        enddesc: "",
      },
      {
        name: "Copyright Infringement",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Stop copyright infringement with top IP attorneys. We will initiate legal notice and apposition T&C*  ",
        middesc:
          "We provide an easy 3-step process, with 2000+ cases resolved annually.",
        enddesc: "",
      },
      {
        name: "Trademark Infringement",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Stop trademark infringement with top trademark attorneys. Legal notice and apposition initiated in 3 quick steps T&C* ",
        middesc:
          "Thorough brand name monitoring, evidence documentation, and legal support provided",
        enddesc: "",
      },
      {
        name: "Logo Design",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Our Logo Designers create a strong visual identity that represents your brand. ",
        middesc: "Top designers ensure quick delivery with iterations",
        enddesc: "",
      },
      {
        name: "Design Registration",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Protect your product's shape, configuration, pattern, or what makes it look different from other product with our design registration service",
        middesc:
          "Our IP experts ensure a transparent process through follow-up and regular updates",
        enddesc: "",
      },
    ],
  },
  5: {
    items: [
      {
        name: "Non Disclosure Agreement NDA",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "If you own a business or are planning to start one, there will be instances when you would need to share your personal information with a third party. Put your troubles aside and concentrate on your business with a non-disclosure agreement.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Service Level Agreement",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Get your SLA drafted in just a click. Save time, money, and effort. T&C* ",
        middesc:
          "Acquire thorough understanding of clauses and avoid legal mistakes",
        enddesc: "",
      },
      {
        name: "Franchise Agreement",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "We at Vakilsearch are here to provide you with the guidance and assistance you need for your perfect franchise agreement.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Master Service Agreement",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "We help you in creating a comprehensive master service agreement that covers as many aspects as possible.By avoiding unnecessary negotiations, the MSA contract saves your company's money and time.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Shareholders Agreement",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Are you an entrepreneur looking to draft a shareholder’s agreement for your startup? Vakilsearch can help you in creating one.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Joint Venture Agreement",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Need help with drafting a joint venture agreement? Reach out to Vakilsearch!",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Founders Agreement",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Do you have a team of entrepreneurs that have come up with a fantastic business idea? A founders agreement is a great way to organize and outline the important specifics of your new business relationship.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Vendor Agreement",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "We will help you with drafting a vendor agreement that will cover aspects of your relationship with a vendor, such as vendor contract length, payment method, etc.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Consultancy Agreement",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Whether you're hiring a consultant or being hired as a consultant, the consultancy agreement should be used to formalize the relationship. We’ve got you covered!",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Memorandum of Understanding",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Get your MoU drafted from experts in just 3 days",
        middesc:
          "Get 2 round of iterations. Transparent process, thorough follow up and regular updates",
        enddesc: "",
      },
      {
        name: "Make a Will",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Expert Will drafting and online registration, hassle-free with 2 free iterations.",
        middesc: "100% Online and safe process with registration support.",
        enddesc: "",
      },
      {
        name: "Power of Attorney",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Vakilsearch will go through your key details and requirements and draft a power of attorney for you.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Terms of Service",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        paragraph: "Get expert help to draft terms of service.",
        desc: "Clauses, disclaimers, refunds related queries clarified",
        middesc: "Seamless interactive process with the government",
        enddesc:
          "Consultation fees paid will be adjusted against the professional fee.",
      },
      {
        name: "GDPR",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "We will help align your data policy as per the requirements of the European Union enactment.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Disclaimer",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Get your website disclaimer policy drafted in just 24 hours",
        middesc:
          "Begin for ₹999 with 2 complimentary iteration sessions included",
        enddesc: "",
      },
    ],
  },
  6: {
    items: [
      {
        name: "Scope of Work and Deliverables Agreement",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Get precise, effective Statement of Work (SOW) Agreements from our Legal experts. Get your First draft in 4 days with 2 free rounds of iteration.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Rental Agreement",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "We at Vakilsearch are here to provide you with the assistance you need to register your rent and lease agreement.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Sale Deed",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Get Guaranteed Sale Deed drafting under 3 days or receive a full refund T&C* ",
        middesc:
          "Fastest turnaround time to draft a Sale Deed by India’s senior lawyers",
        enddesc: "",
      },
      {
        name: "Legal Notice",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Make your complaint heard by drafting it with senior lawyers of Vakilsearch. Receive a Guaranteed draft of your notice in 2 days or receive a full refund T&C* ",
        middesc: "Qualified arbitrators assistance for quick resolution",
        enddesc: "",
      },
      {
        name: "Legal Notice for recovery of dues",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "A legal notice is a letter sent to another individual intending to take legal action against them. With the help of Vakilsearch, you can send a legal notice per your needs.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Cheque Bounce Notice",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Draft a cheque bounce notice with experienced lawyers of Vakilsearch to recover your money. Get a guaranteed draft of your notice in 3 working days T&C* ",
        middesc:
          "In case of no response, our lawyers will assist you with the judicial procedure in the appropriate legal format.",
        enddesc: "",
      },
      {
        name: "Employment Agreement",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Easily draft an employment agreement online and seal the relationship between employees and employers",
        middesc: "",
        enddesc: "",
      },
      {
        name: "ESOP",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "ESOP is an effective employee retention strategy with which a company provides stock options to its employees so that they stick around and remain motivated.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Fundraising",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Complete assistance with Pitch Deck creation and financial projections from India’s top business experts",
        middesc: "India’s only Investor-Connect service available on request",
        enddesc: "",
      },
      {
        name: "Pitch Deck",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Get an expert to build your investment pitch deck from Vakilsearch and impress your potential investors.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "NGO",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Stop copyright infringement with top IP attorneys. We will initiate legal notice and apposition T&C* ",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Section 8",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Fastest registration turnaround time in India with Guaranteed document upload to the government portal under 7 days or get a full refund T&C* ",
        middesc:
          "Get assistance with tax-saving options, and much more Post-registration",
        enddesc: "",
      },
      {
        name: "Trust Registration",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Draft your deed in 3 days and start operating your Trust",
        middesc: "Transparent process, thorough follow up and regular updates",
        enddesc: "",
      },
      {
        name: "Society Registration",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Get fast and easy society registration with Guaranteed document upload to the government portal under 7 days",
        middesc:
          "Get assistance with tax-saving options, and much more Post-registration",
        enddesc: "",
      },
      {
        name: "NGO Compliance",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "NGO compliance refers to the adherence to laws, regulations, and standards set by governments and other organisations that govern the operations and activities of NGOs.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Section 8 Complaince",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Work for your mission uninterrupted while our experts take care of your Section 8 company annual compliance tasks. Get our annual compliance package now.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "CSR-1 Filing",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "Get CSR 1 Registration for NGOs done at Vakilsearch. Our dedicated team provides you with unmatchable service and expertise and is your one-stop solution for CSR registrations.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Sec.80G & Sec.12A",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "NGOs are established for good causes, and the government provides tax exemptions to assist them with raising funds. Now is the time to register your NGO under Sections 80G and 12A in order to avail of those benefits for your NGO.",
        middesc: "",
        enddesc: "",
      },
      {
        name: "Darpan Registration",
        id: 3,
        img: "/assets/img/blog/blog_post01.jpg",
        user: "Artwork",
        date: "28 Sept 2023",
        comments: "3",
        title: "Minimal workspace for inspiration",
        desc: "NGOs work for a good cause and are needed to be enrolled on the government’s registry of NGOs: Darpan. Vakilsearch with its seamless Darpan registration helps your organisation work for your dream.",
        middesc: "",
        enddesc: "",
      },
    ],
  },
};
export default service_data;
